type Query {
  todos: [Todo!]!
}

type Mutation {
  createTodo(todo: TodoInput!): Boolean!
  deleteTodo(id: Int!): Boolean!
  updateTodo(todo: TodoInput!): Boolean!
}

input TodoInput {
  id: String!
  text: String!
  done: Boolean!
}

type Todo {
  id: String!
  text: String!
  done: Boolean!
}
